### ISSUE TITLE
implement wordcloud filter

### ISSUE THREAD

**Issue by MaxHoffmannNanologika** [ASKtraining/Training#11]

**Comment by MaxHoffmannNanologika** [comment]
functionality is implemnted in wordcloud branch. now lets see if we can merge it

**Comment by bmen** [comment]
Great, I tested it locally :+1: 

One thing is still missing and that is when you click on "All" then all selected tags are disabled and you see all modules again.

> functionality is implemnted in wordcloud branch. now lets see if we can merge it

**Comment by MaxHoffmannNanologika** [comment]
added that.
