### ISSUE TITLE
generate pauses

### ISSUE THREAD

**Issue by MaxHoffmannNanologika** [ASKtraining/Training#13]
- pauses are deletable
- length is editable

**Comment by bmen** [comment]
I also made the resource list as a StackedList and now you can move all the items in the three areas (Sidebar, Content Module List and Content Resource List). With the pauses it's work great. Unfortunately modules can now get into the resource list or resources into the sidebar. So we have to lock some lists for some object types.

**Comment by MaxHoffmannNanologika** [comment]
at the moment I can't move modules from the sidebar to the training. moving pauses and daybreaks around works though

**Comment by bmen** [comment]
> at the moment I can't move modules from the sidebar to the training. moving pauses and daybreaks around works though

i fixed it in the last commit

**Comment by MaxHoffmannNanologika** [comment]
automatic break insertion now implemented based on the `data-duration` custom html attribute as mentioned here: #13
