### ISSUE TITLE
Design objects at the moment when they are moved

### ISSUE THREAD

**Issue by bmen** [ASKtraining/Training#14]

**Comment by bmen** [comment]
@MaxHoffmannNanologika i need the css class when the object is moved

**Comment by MaxHoffmannNanologika** [comment]
in the example by draggable.js they do this: 
`.draggable--is-dragging & .draggable-container-parent--capacity {
    color: get-color(brand, blue);
  }`

https://github.com/Shopify/draggable/blob/master/examples/src/content/Sortable/MultipleContainers/MultipleContainers.scss

**Comment by MaxHoffmannNanologika** [comment]
now with sortable.js the class is `.sortable-ghost`

**Comment by bmen** [comment]
if the user hovers an object that you can move show the grab hand as mouse pointer
