### ISSUE TITLE
Research which css library we want to use

### ISSUE THREAD

**Issue by bmen** [ASKtraining/Training#2]

**Comment by bmen** [comment]
* https://tailwindcss.com/
* https://www.w3schools.com/w3css/defaulT.asp
* https://getbootstrap.com/

**Comment by coesterheld** [comment]
for inspiration see also: [publicly available design systems and pattern libraries](https://adele.uxpin.com/)

**Comment by bmen** [comment]
we don't use a css library. It's all own code but written in sass
