### ISSUE TITLE
create form for start time

### ISSUE THREAD

**Issue by bmen** [ASKtraining/Training#21]
we need 3 inputs:

* Hours
* Minutes
* Dropdown: am/pm

with html validation

**Comment by MaxHoffmannNanologika** [comment]
input field attrbiutes for validation:
https://www.w3schools.com/html/html_form_attributes.asp

**Comment by bmen** [comment]
@MaxHoffmannNanologika i added the dropdown for am/pm and set attributes for min/max hours and minutes
