### ISSUE TITLE
add data attributes to modules and resources for summary

### ISSUE THREAD

**Issue by bmen** [ASKtraining/Training#22]
- [x] Max. participants number in module
- [x] Min. trainers number in module
- [x] difficulty level for trainers string in module
- [x] minimum training space number in module
- [x] internet needed boolean in resource
- [x] power supply needed boolean in resource
- [x] material costs number in resource

**Comment by MaxHoffmannNanologika** [comment]
here are the attributes with their value ranges:
- Max. participants number in module : integer (>0)
- Min. trainers number in module : integer (>0)
- difficulty level for trainers string in module : [1, 5] -> maps to difficulty levels: 
1: low,
2: low-medium,
3: medium,
4: medium-high,
5: high
- minimum training space number in module: integer (square meters, >0)
- internet needed boolean in resource: {'yes', 'no'}
- power supply needed boolean in resource: : {'yes', 'no'}
- material costs number in resource: integer (>0)
