### ISSUE TITLE
Move position of Time total text and count days separately 

### ISSUE THREAD

**Issue by timmwille** [ASKtraining/Training#39]
![grafik](https://user-images.githubusercontent.com/8081055/120020974-bed7d380-bfea-11eb-89fa-6782a66791f4.png)

1) move text to hours and minutes
2) put the Day counter upfront and make it bigger (key identifier are the starting days, the hours and minutes are counted separately) and put the Clock Icon in the middle/aside the hh:mm counter :+1: 
3) Level of Difficulty (for now is enough not to point out the Trainer specific level in this case, can be explained in the documentation)

**Comment by timmwille** [comment]
I think this would make it look a bit cleaner and indicate the days to be planned for the action on first look

Might also be good to give the days an calendar icon and put the text "days" or "Training days" under the counter to make it all look similar to the other indicator icons

**Comment by MartinSchott** [comment]
moved here https://github.com/ASKnetCommunity/Training/issues/13
