### ISSUE TITLE
Create strategy for drag and drop

### ISSUE THREAD

**Issue by bmen** [ASKtraining/Training#4]

**Comment by MaxHoffmannNanologika** [comment]
https://shopify.github.io/draggable/examples/multiple-containers.html

hier mit jekyll + github pages bsp.:
https://github.com/Shopify/draggable/blob/master/examples/src/content/Sortable/MultipleContainers/MultipleContainers.html
https://github.com/Shopify/draggable/blob/master/examples/src/components/StackedList/StackedListItem.html
