### ISSUE TITLE
implement the module boxes in the dragable.js design pattern

### ISSUE THREAD

**Issue by bmen** [ASKtraining/Training#5]

**Comment by MaxHoffmannNanologika** [comment]
Hauptseite Bsp.:
https://github.com/Shopify/draggable/blob/master/examples/src/content/Sortable/MultipleContainers/MultipleContainers.html
Component bsp.:
https://github.com/Shopify/draggable/blob/master/examples/src/components/StackedList/StackedListItem.html

**Comment by bmen** [comment]
If i insert 
```
{% import 'components/StackedList/StackedListItem.html' as StackedListItem %}
```
then i get this error:
```
Liquid Exception: Liquid syntax error (line 1): Unknown tag 'import' in index.html
jekyll_1  |              Error: Liquid syntax error (line 1): Unknown tag 'import'
jekyll_1  |              Error: Run jekyll build --trace for more information.
```

**Comment by MaxHoffmannNanologika** [comment]
Hm bei genauerer betrachtung kann es gut sein das da webpack verwendet wird zum builden der seite. So ganz habe ich das noch nicht durchschaut. Aber dann lass es erstmal weg.

Von: bmen <notifications@github.com>
Gesendet: Dienstag, 16. Februar 2021 17:23
An: ASKtraining/Training <Training@noreply.github.com>
Cc: Maximilian Hoffmann <maximilian.hoffmann@nanologika.de>; Comment <comment@noreply.github.com>
Betreff: Re: [ASKtraining/Training] implement the module boxes in the dragable.js design pattern (#5)


If i insert

{% import 'components/StackedList/StackedListItem.html' as StackedListItem %}

then i get this error:

Liquid Exception: Liquid syntax error (line 1): Unknown tag 'import' in index.html

jekyll_1  |              Error: Liquid syntax error (line 1): Unknown tag 'import'

jekyll_1  |              Error: Run jekyll build --trace for more information.
