### ISSUE TITLE
time edit and calculations

### ISSUE THREAD

**Issue by bmen** [ASKtraining/Training#8]

**Comment by MaxHoffmannNanologika** [comment]
the event 'sortable:sorted' may be useful for this application

https://github.com/Shopify/draggable/tree/master/src/Sortable

**Comment by MaxHoffmannNanologika** [comment]
since we use sortableJS now the `onEnd` Event is most useful

**Comment by MaxHoffmannNanologika** [comment]
but we still need a place where the information about the duration of a reource or module is stored. 
I suggest using the data-* attribute of an HTML element. For example:
`<div class="resource" data-duration="120">...` 

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by MaxHoffmannNanologika** [comment]
how do we handle daybreaks? will the training start at the same time it did the day before? will there be another "trainingstart" module to enable custom starting times each day?

**Comment by MaxHoffmannNanologika** [comment]
add module introduction duration

**Comment by MaxHoffmannNanologika** [comment]
> 
> 
> how do we handle daybreaks? will the training start at the same time it did the day before? will there be another "trainingstart" module to enable custom starting times each day?

dabreaks = trainingstart

daybreaks have default time 9:00am

**Comment by MaxHoffmannNanologika** [comment]
- remove css for time edit hover -> now replaced by onclick function
- inputs not editable (?)

**Comment by MaxHoffmannNanologika** [comment]
the input buttons sometimes dont work. but functionality is implemented
